#!/bin/sh
# Machine-generated ABI baseline for one macOS release.
#
# Emits one line per vtable slot, plus recovered instance sizes, in a form whose
# whole point is that two releases' output can be `diff`ed. That turns porting to
# a new release from "re-derive every layout" into "read the delta", which is the
# only affordable way to survive a macOS update — and Apple has changed this ABI
# inside a point release before (hence the separate Sonoma14.0 / Sonoma14.4
# targets in this project).
#
#   scripts/abi/snapshot.sh [kernel-collection] > scripts/abi/abi-<ver>-<build>.txt
#
# Defaults to the running system's collection. RUN IT BEFORE INSTALLING AN UPDATE:
# /System/Library/KernelCollections is replaced wholesale, and nothing else on the
# machine carries the old layout.
#
# Companion to tahoe-26.6-slots.txt, which is the hand-curated own-slots view with
# commentary. This one is exhaustive and unannotated on purpose: no judgement to go
# stale, so it stays valid as a comparison base forever.
set -eu

KC=${1:-/System/Library/KernelCollections/BootKernelExtensions.kc}
HERE=$(cd "$(dirname "$0")" && pwd)
PY=$HERE/.venv/bin/python3
[ -x "$PY" ] || PY=python3

# Classes this repo reconstructs in include/Airport, i.e. every class whose layout a
# release change can break today.
RECONSTRUCTED="
IOSkywalkInterface
IOSkywalkNetworkInterface
IOSkywalkEthernetInterface
IOSkywalkLegacyEthernetInterface
IO80211SkywalkInterface
IO80211InfraInterface
IO80211InfraProtocol
IO80211Controller
IO80211VirtualInterface
IO80211P2PInterface
IO80211Interface
IOSkywalkNetworkPacket
IOSkywalkPacketBufferPool
CCPipe
CCLogPipe
CCDataPipe
CCStream
CCLogStream
CCDataStream
CCFaultReporter
IO80211FaultReporter
"

# The Skywalk data path. Not reconstructed today — this is exactly what a real
# registerEthernetInterface would require (root AGENTS.md mechanism 1) — so it is
# captured to keep that option open across the update rather than because the repo
# depends on it yet.
DATAPATH="
IOSkywalkLogicalLink
IOSkywalkQueueSet
IOSkywalkPacketQueue
IOSkywalkTxSubmissionQueue
IOSkywalkRxSubmissionQueue
IOSkywalkTxCompletionQueue
IOSkywalkRxCompletionQueue
IOSkywalkPacket
IOSkywalkMemorySegment
IOSkywalkController
IOSkywalkNetworkController
IOSkywalkBSDClient
IOSkywalkNetworkBSDClient
"

# Concrete Apple subclasses. Abstract bases show ___cxa_pure_virtual for the slots
# whose names matter most, so these are what actually name them — and they double as
# the reference for how a real driver drives the family.
REFERENCE="
AppleBCMWLANCore
AppleBCMWLANInfraProtocol
AppleBCMWLANSkywalkInterface
AppleBCMWLANSkywalkPacketPool
AppleBCMWLANSkywalkTxSubmissionQueue
AppleBCMWLANSkywalkRxSubmissionQueue
AppleBCMWLANSkywalkTxCompletionQueue
AppleBCMWLANSkywalkRxCompletionQueue
AppleBCMWLANSkywalkMulticastQueue
"

ALL="$RECONSTRUCTED $DATAPATH $REFERENCE"

echo "# ABI baseline"
echo "# collection: $KC"
if [ "$KC" = /System/Library/KernelCollections/BootKernelExtensions.kc ]; then
    echo "# system:     $(sw_vers -productVersion) ($(sw_vers -buildVersion))"
fi
echo "# generated by scripts/abi/snapshot.sh"
echo

echo "########## instance sizes"
# shellcheck disable=SC2086
"$PY" "$HERE/classsize.py" "$KC" $ALL 2>/dev/null | sed 's/^/  /'
echo

echo "########## vtable slots"
for c in $ALL; do
    "$PY" "$HERE/vtdump.py" "$KC" "$c" 2>/dev/null |
        sed -n "s/^  \[ *\([0-9][0-9]*\)\] \(.*\)$/$c \1 \2/p"
done
